'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const test = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM, VirtualConsole } = require('jsdom');
const C = require('../src/core.js');
const ROOT = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const scripts = [...html.matchAll(/<script src="([^"]+)" defer><\/script>/g)].map(m => [m[1], fs.readFileSync(path.join(ROOT,m[1]),'utf8')]);
const dataset = {window:{}};
vm.createContext(dataset);
scripts.filter(([p])=>p.startsWith('data/')).forEach(([,code])=>vm.runInContext(code,dataset));
const catalog = dataset.window.JGP_CATALOG, blocks = dataset.window.JGP_CHARACTERISTICS.blocks;
const pay = dataset.window.HOSPITALAPP_PAYROLL;
const g = code => catalog.groups.find(x=>x.code===code);
const example = {volume:1000,revenue:5000,fixed:1200000,variable:1500,days:5,dayCost:200,targetDays:4,targetVariable:1500};
const tick = () => new Promise(resolve=>setTimeout(resolve,0));
async function app(options={}) {
  const errors=[];
  const vc = new VirtualConsole(); vc.on('jsdomError',e=>errors.push(e));
  const dom = new JSDOM(html,{runScripts:'outside-only',url:'https://example.test/szpitale/',virtualConsole:vc,pretendToBeVisual:true});
  const w=dom.window;
  w.confirm=()=>true;w.print=()=>{};w.URL.createObjectURL=()=> 'blob:https://example.test/export';w.URL.revokeObjectURL=()=>{};
  if(options.stored)w.localStorage.setItem('hospitalapp-workspace-v2',JSON.stringify(options.stored));
  if(options.legacy)w.localStorage.setItem('hospitalapp-jgp-v06',JSON.stringify(options.legacy));
  if(options.notes)w.localStorage.setItem('hospitalapp-local-notes-v1',JSON.stringify(options.notes));
  const law=options.law || JSON.parse(fs.readFileSync(path.join(ROOT,'data/mz-legislation.json'),'utf8'));
  w.fetch=async()=>{if(options.fetchError)throw Error('offline');return {ok:true,json:async()=>law};};
  scripts.forEach(([,code])=>w.eval(code)); await tick();
  const $ = selector=>w.document.querySelector(selector);
  const input=(selector,value)=>{const el=$(selector);assert.ok(el,selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
  const change=(selector,value)=>{const el=$(selector);el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));};
  const click=selector=>{assert.ok($(selector),selector);$(selector).click();};
  const route=async name=>{w.location.hash=name;w.dispatchEvent(new w.HashChangeEvent('hashchange'));await tick();};
  return {dom,w,$,input,change,click,route,errors,close:()=>{assert.deepEqual(errors,[]);w.close();}};
}
test('catalog retains 748 groups and 1ae; retired obstetric groups absent',()=>{
  assert.equal(catalog.groups.length,748);assert.equal(catalog.meta.orderNumber,'74/2026/DSOZ');
  for(const code of ['N09','N11','N13'])assert.equal(g(code),undefined);
  assert.equal(g('N01').ordinary,4352);assert.ok(g('AU35C'));
});
test('null values never become a free tariff mode',()=>{assert.ok(!C.availableModes(g('A01')).some(([m])=>m==='planned'));assert.equal(C.tariff(g('A01'),'planned',2),null);});
test('1ae defaults to under12h, not a duplicate ordinary mode',()=>{assert.equal(C.availableModes(g('AU35C'))[0][0],'under12h');assert.ok(!C.availableModes(g('AU35C')).some(([k])=>k==='ordinary'));});
test('N01 arithmetic with explicit user price',()=>{assert.equal(C.tariff(g('N01'),'ordinary',1.96).total,8529.92);});
test('empty, negative and nonfinite price is rejected; explicit zero allowed',()=>{for(const x of ['',null,-1,'abc',Infinity])assert.equal(C.tariff(g('N01'),'ordinary',x),null);assert.equal(C.tariff(g('N01'),'ordinary',0).total,0);});
test('Polish decimals and diacritics work',()=>{assert.equal(C.numeric('1 234,50'),1234.5);assert.equal(C.normalize('ŁÓDŹ'),'lodz');});
test('sum deviations and multiplication preserve documented order',()=>{assert.ok(Math.abs(C.combinedFactor([{value:1.2,operation:'sum'},{value:1.1,operation:'sum'},{value:1.05,operation:'multiply'}])-1.365)<1e-10);});
test('invalid coefficients do not produce plausible results',()=>{assert.equal(C.combinedFactor([{value:'',operation:'sum'}]),null);assert.equal(C.combinedFactor([{value:0,operation:'multiply'}]),null);assert.equal(C.combinedFactor([{value:1,operation:'unknown'}]),null);});
test('scenario computes annual change and correct break-even',()=>{const r=C.scenario(example);assert.equal(r.current,1300000);assert.equal(r.target,1500000);assert.equal(r.impact,200000);assert.equal(r.freedDays,1000);assert.equal(r.breakEven,445);assert.equal(r.margin,30);});
test('zero avoidable day cost gives no saving from shorter stay',()=>{assert.equal(C.scenario({...example,dayCost:0}).impact,0);});
test('longer stay reduces model result',()=>{assert.equal(C.scenario({...example,targetDays:6}).impact,-200000);});
test('unreachable break-even and undefined zero-revenue margin are explicit',()=>{const r=C.scenario({...example,revenue:0});assert.equal(r.breakEven,null);assert.equal(r.margin,null);});
test('missing, negative and fractional-volume scenario inputs rejected',()=>{for(const v of ['',0,-1,1.5,'x'])assert.equal(C.scenario({...example,volume:v}),null);assert.equal(C.scenario({...example,dayCost:-10}),null);assert.equal(C.scenario({...example,fixed:''}),null);});
test('payroll rounds per-FTE base amounts to cents before multiplying',()=>{const r=C.payroll(pay.groups,{previousBase:8181.72,currentBase:8903.56,oncost:20.48,includeOncost:false,headcounts:{'1':10}});assert.equal(r.rows[0].before,11863.49);assert.equal(r.rows[0].after,12910.16);assert.ok(Math.abs(r.monthly-10466.7)<1e-6);assert.equal(r.fte,10);});
test('payroll oncost toggle and six vs twelve months',()=>{const i={previousBase:100,currentBase:200,oncost:20,includeOncost:true,headcounts:{'1':1}};const r=C.payroll(pay.groups,i);assert.equal(r.monthly,174);assert.equal(r.annual,2088);assert.equal(r.secondHalf,1044);assert.equal(C.payroll(pay.groups,{...i,includeOncost:false}).monthly,145);});
test('negative FTE and missing payroll bases rejected',()=>{assert.equal(C.payroll(pay.groups,{previousBase:100,currentBase:'',oncost:0,headcounts:{}}),null);assert.equal(C.payroll(pay.groups,{previousBase:100,currentBase:200,oncost:0,headcounts:{'1':-2}}),null);});
test('search exact group ranks first, ICD references are included',()=>{const search=C.createSearch(catalog.groups,blocks);assert.equal(search('N01')[0].group.code,'N01');assert.ok(search('O80','diagnosis').some(x=>x.group.code==='N01'));assert.ok(search('72.1','procedure').length);assert.equal(search('N09').some(x=>x.group.code==='N09'),false);});
test('search handles cyclic references and searches transitive lists',()=>{const b={A:{references:[{code:'B'}],segments:[]},B:{references:[{code:'A'}],segments:[{type:'list',system:'ICD-10',items:['X00 test']}]}};assert.equal(C.referencedBlocks('A',b).length,2);assert.equal(C.createSearch([{code:'A',name:'Alpha'}],b)('X00','diagnosis').length,1);});
test('freshness does not label old, missing or future dates as fresh',()=>{const now=Date.parse('2026-09-04T12:00:00Z');assert.ok(C.freshness('2026-09-04T10:00:00Z',now));for(const v of [null,'bad','2026-08-31','2027-01-01'])assert.equal(C.freshness(v,now),false);});
test('CSV protects formulas and escapes quotes/newlines',()=>{const csv=C.csv([['=HYPERLINK("x")','normal','+SUM(1)',-5,'a\nb']]);assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes("'=HYPERLINK"));assert.ok(csv.includes("'+SUM"));assert.ok(csv.includes('"-5"'));assert.ok(csv.includes('"a\nb"'));});
test('working home and eight routes, no retired UI modules',async()=>{const a=await app();assert.match(a.$('h1').textContent,/Dzień dobry/);assert.ok(a.$('#home-search'));assert.equal(a.w.document.querySelectorAll('.nav-link').length,8);assert.doesNotMatch(a.$('#workspace').textContent,/Przetargi|Świadczenia NFZ|Umowy NFZ/);a.close();});
test('all routes render with no runtime errors',async()=>{const a=await app();for(const route of ['gruper','porownanie','scenariusze','legislacja','koszty','place','notatki','ud439']){await a.route(route);assert.ok(a.$('h1'));assert.ok(a.$('#workspace').textContent.length>100);}a.close();});
test('JGP value, favorites and compare flow',async()=>{const a=await app();a.click('[data-code="N01"]');await tick();a.input('#point-price','1.96');assert.match(a.$('#tariff-total').textContent,/8[\s\u00a0]?529,92/);a.click('[data-action="favorite"]');assert.equal(a.$('[data-action="favorite"]').getAttribute('aria-pressed'),'true');a.click('[data-action="compare-add"]');await a.route('porownanie');assert.equal(a.w.document.querySelectorAll('.compare-card').length,1);assert.match(a.$('.compare-card').textContent,/N01/);a.close();});
test('ICD lists are lazy and open to source content',async()=>{const a=await app();a.click('[data-code="A01"]');await tick();const list=a.$('.icd-list');assert.equal(list.querySelectorAll('li').length,0);list.open=true;list.dispatchEvent(new a.w.Event('toggle'));assert.ok(list.querySelectorAll('li').length>0);a.close();});
test('1ae renders only supported mode',async()=>{const a=await app();a.click('[data-code="AU35C"]');await tick();assert.match(a.$('#tariff-mode').textContent,/12 godzin/);assert.equal(a.$('#tariff-mode').value,'under12h');a.close();});
test('JGP to scenario carries amount and provenance',async()=>{const a=await app();a.click('[data-code="N01"]');await tick();a.input('#point-price','1.96');a.click('[data-action="scenario-from-group"]');await tick();assert.equal(a.$('#scenario-revenue').value,'8529.92');assert.match(a.$('#scenario-origin').textContent,/N01.*74\/2026/);a.close();});
test('scenario starts empty; example is labelled and saves locally',async()=>{const a=await app();await a.route('scenariusze');assert.ok(a.$('.scenario-placeholder'));a.click('[data-action="demo-scenario"]');assert.match(a.$('#scenario-origin').textContent,/DEMONSTRACYJNE/);assert.match(a.$('.impact-card strong').textContent,/200[\s\u00a0]000/);a.click('[data-action="save-scenario"]');assert.equal(a.w.document.querySelectorAll('#saved-scenarios tbody tr').length,1);assert.equal(JSON.parse(a.w.localStorage.getItem('hospitalapp-workspace-v2')).scenarios.length,1);a.close();});
test('notes escape markup, persist and toggle completion',async()=>{const a=await app();await a.route('notatki');a.input('#note-text','<img src=x onerror=alert(1)>');a.click('[data-action="add-note"]');assert.equal(a.w.document.querySelectorAll('.note-card img').length,0);assert.match(a.$('.note-card p').textContent,/<img/);a.click('[data-action="note-done"]');assert.ok(a.$('.note-card.done'));a.close();});
test('legislation freshness, important filter and unsafe link rejection',async()=>{const a=await app({law:{meta:{checkedAt:'2020-01-01'},items:[{id:'x',title:'Projekt testowy',url:'javascript:alert(1)',summary:'<script>bad</script>',summaryStatus:'ready'}]}});await a.route('legislacja');assert.match(a.$('.source-note').textContent,/nieaktualne/);assert.equal(a.$('.law-card a[href^="javascript:"]'),null);a.click('[data-key="important"]');a.change('#law-filter','important');assert.equal(a.w.document.querySelectorAll('.law-card').length,1);assert.equal(a.$('.law-card script'),null);a.close();});
test('network failure gives retry instead of fake projects',async()=>{const a=await app({fetchError:true});await a.route('legislacja');assert.match(a.$('#law-results').textContent,/Nie udało/);assert.ok(a.$('[data-action="refresh-law"]'));a.close();});
test('payroll UI reacts to FTE and invalid inputs',async()=>{const a=await app();await a.route('place');a.input('[data-fte="1"]','10');assert.match(a.$('#payroll-summary').textContent,/12[\s\u00a0]610/);a.input('#pay-current','');assert.match(a.$('#payroll-summary').textContent,/—/);a.close();});
test('knowledge exposes full text and twenty FAQ entries',async()=>{const a=await app();await a.route('koszty');a.click('[data-knowledge="faq"]');assert.equal(a.w.document.querySelectorAll('.knowledge-card').length,20);a.input('#knowledge-search','OPK');assert.ok(a.w.document.querySelectorAll('.knowledge-card').length>0);a.close();});
test('legacy price, coefficients and notes are preserved',async()=>{const a=await app({legacy:{customPrice:2.5,groupCode:'N01',coefficientsByGroup:{N01:[{value:1.2,combination:'multiply'}]}},notes:[{id:'old',text:'Moja stara notatka',createdAt:'2026-08-01'}]});await a.route('gruper');assert.equal(a.$('#point-price').value,'2.5');assert.match(a.$('#tariff-total').textContent,/13[\s\u00a0]056/);await a.route('notatki');assert.match(a.$('.note-card').textContent,/stara notatka/);a.close();});
test('corrupt record collections recover without breaking routes',async()=>{const a=await app({stored:{scenarios:[null,{}],notes:[null,{}],favorites:'bad',compare:[null,'N09'],scenarioDraft:'bad'}});await a.route('scenariusze');assert.ok(a.$('.scenario-placeholder'));await a.route('notatki');assert.ok(a.$('.empty'));a.close();});
test('public shell has CSP, working local references and versioned worker',()=>{assert.match(html,/Content-Security-Policy/);for(const [file]of scripts)assert.ok(fs.existsSync(path.join(ROOT,file)));const sw=fs.readFileSync(path.join(ROOT,'sw.js'),'utf8');assert.match(sw,/hospitalapp-v2\.0\.0/);assert.doesNotMatch(sw,/nfz-contract|procurements|financial-results/);for(const[file]of scripts)assert.ok(sw.includes('./'+file),file);assert.match(sw,/key\.startsWith\('hospitalapp-v'\)/);});
